spring:
  application:
    name: iot_platform_consumer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot-platform
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

consumer:
  group-id: iot-platform-consumers

server:
  port: 0